from pydantic import BaseModel, Field

# This is what the Frontend sends to the Backend
class QueryRequest(BaseModel):
    # Field(...) ensures the user can't send an empty string
    question: str = Field(..., min_length=2, description="The plain English data question from the user")

# This is what the Backend sends back to the Frontend
class QueryResponse(BaseModel):
    status: str = Field(..., description="'success' or 'error'")
    answer: str = Field(..., description="The plain English answer or SQL data string")
    mode: str = Field(..., description="Shows if it was generated by Ollama or Gemini")